//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateModelsDBEFApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_University
    {
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public int UniversityId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Hour { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual University University { get; set; }
    }
}
